version: '3.8'

services:
  vllm:
    image: vllm/vllm-openai:latest
    container_name: vllm
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - HUGGING_FACE_HUB_TOKEN=
      - HUGGINGFACE_HUB_TOKEN=
      - HF_TOKEN=
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    shm_size: '2gb'
    ipc: host
    command:
      - "--model"
      - "RedHatAI/Qwen3-8B-NVFP4"
      - "--tensor-parallel-size"
      - "1"
      - "--max-model-len"
      - "8192"
      - "--gpu-memory-utilization"
      - "0.7"
      - "--max-num-seqs"
      - "64"
      - "--trust-remote-code"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8000"

